package com.hms.ui;

import com.hms.utils.Theme;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

public class ReportsScreen extends JPanel {

    public ReportsScreen() {
        setLayout(new BorderLayout(15, 15));
        setBackground(Theme.BACKGROUND);
        setBorder(new EmptyBorder(20, 25, 20, 25));

        JLabel title = new JLabel("REPORTS");
        title.setFont(Theme.TITLE);
        title.setForeground(Theme.PRIMARY_GREEN);

        JPanel filterPanel = new JPanel(new GridBagLayout());
        filterPanel.setBackground(Color.WHITE);
        filterPanel.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(215, 215, 215)),
                new EmptyBorder(20, 25, 20, 25)
        ));

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.fill = GridBagConstraints.HORIZONTAL;

        JComboBox<String> reportType = new JComboBox<>(new String[]{
                "Patient Report",
                "Doctor Report",
                "Appointment Report",
                "Billing Report",
                "Medical Store Report"
        });

        JTextField fromDate = field();
        JTextField toDate = field();

        addRow(filterPanel, gbc, 0, "Report Type:", reportType, "From Date:", fromDate);
        addRow(filterPanel, gbc, 1, "To Date:", toDate, "", new JLabel(""));

        JPanel buttons = new JPanel(new FlowLayout(FlowLayout.CENTER, 15, 5));
        buttons.setBackground(Color.WHITE);

        JButton generate = button("Generate Report");
        JButton clear = button("Clear");
        JButton print = button("Print");

        buttons.add(generate);
        buttons.add(clear);
        buttons.add(print);

        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridwidth = 4;
        filterPanel.add(buttons, gbc);

        DefaultTableModel model = new DefaultTableModel(
                new String[]{"Report Type", "From Date", "To Date", "Generated By"}, 0
        );

        JTable table = new JTable(model);
        table.setRowHeight(28);

        generate.addActionListener(e -> model.addRow(new Object[]{
                reportType.getSelectedItem(),
                fromDate.getText(),
                toDate.getText(),
                "Admin"
        }));

        clear.addActionListener(e -> {
            reportType.setSelectedIndex(0);
            fromDate.setText("");
            toDate.setText("");
        });

        JPanel center = new JPanel(new BorderLayout(15, 15));
        center.setBackground(Theme.BACKGROUND);
        center.add(filterPanel, BorderLayout.NORTH);
        center.add(new JScrollPane(table), BorderLayout.CENTER);

        add(title, BorderLayout.NORTH);
        add(center, BorderLayout.CENTER);
    }

    private void addRow(
            JPanel panel,
            GridBagConstraints gbc,
            int row,
            String label1,
            JComponent field1,
            String label2,
            JComponent field2
    ) {
        gbc.gridy = row;
        gbc.gridwidth = 1;

        gbc.gridx = 0;
        panel.add(label(label1), gbc);

        gbc.gridx = 1;
        panel.add(field1, gbc);

        gbc.gridx = 2;
        panel.add(label(label2), gbc);

        gbc.gridx = 3;
        panel.add(field2, gbc);
    }

    private JTextField field() {
        JTextField field = new JTextField(18);
        field.setFont(Theme.NORMAL);
        return field;
    }

    private JLabel label(String text) {
        JLabel label = new JLabel(text);
        label.setFont(Theme.NORMAL);
        label.setForeground(Theme.TEXT);
        return label;
    }

    private JButton button(String text) {
        JButton btn = new JButton(text);
        btn.setFont(Theme.NORMAL);
        btn.setBackground(Theme.PRIMARY_GREEN);
        btn.setForeground(Color.WHITE);
        btn.setFocusPainted(false);
        return btn;
    }
}